newspaper/urls.py
from django.conf.urls.static import static
from django.urls import path
from django.conf import settings
from . import views

app_name = "newspaper"


urlpatterns = [
    path("", views.index, name="index"),
    path("topics/", views.TopicListView.as_view(), name="topic-list"),
    path("topics/create/", views.TopicCreateView.as_view(), name="topic-create"),
    path("topics/<int:pk>/update/", views.TopicUpdateView.as_view(), name="topic-update"),
    path("topics/<int:pk>/delete/", views.TopicDeleteView.as_view(), name="topic-delete"),
    path("topics/<int:pk>/", views.TopicDetailView.as_view(), name="topic-detail"),
    path("newspapers/create/", views.NewspaperCreateView.as_view(), name="newspaper-create"),
    path("newspapers/<int:pk>/", views.NewspaperDetailView.as_view(), name="newspaper-detail"),
    path("newspapers/<int:pk>/update/", views.NewspaperUpdateView.as_view(), name="newspaper-update"),
    path("newspapers/<int:pk>/delete/", views.NewspaperDeleteView.as_view(), name="newspaper-delete"),
    path("newspapers/", views.NewspaperListView.as_view(), name="newspaper-list"),
    path("redactors/<int:pk>/", views.RedactorDetailView.as_view(), name="redactor-detail"),
    path("redactors/list/", views.RedactorListView.as_view(), name="redactor-list"),
    path("redactors/<int:pk>/delete/", views.RedactorDeleteView.as_view(), name="redactor-delete"),
    path("redactors/<int:pk>/update/", views.RedactorUpdateView.as_view(), name="redactor-update"),
    path("sign-in/", views.LoginView.as_view(), name="sign-in"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("sign-up/", views.RedactorCreateView.as_view(), name="sign-up"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newspaper_agency/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('newspaper.urls', namespace='newspaper')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/footer.html
  <footer class="footer pt-5 mt-5">
    <hr class="horizontal dark mb-5">
    <div class="container">
      <div class=" row">
        <div class="col-md-3 mb-4 ms-auto">
          <div>
            <h6 class="text-gradient text-primary font-weight-bolder">Soft UI Design System</h6>
          </div>
        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4">

        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4">

        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4 me-auto">
        </div>
        <div class="col-12">
          <div class="text-center">
            <p class="my-4 text-sm">
              Soft UI Design System by &copy; <a target="_blank" href="https://bit.ly/3fKQZaL" target="_blank">Creative Tim</a> 
              - Coded by <a target="_blank" href="https://github.com/oigod/newspaper-agency-project/tree/develop">OiGod</a>.
            </p>
          </div>
        </div>
      </div>
    </div>
  </footer>

templates/includes/header.html
<!-- START HEADER SECTION -->
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a href="/"><i class="fa-solid fa-newspaper fa-fade" style="color: #238fe1; font-size: 50px"></i></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      {% if request.user.is_authenticated %}
        <a class="btn btn-danger" href="{% url 'newspaper:logout' %}">Logout!</a>
      {% endif %}
    </div>
  </div>
</nav>
<!-- END HEADER SECTION -->

templates/includes/navigation.html
  <div class="container position-sticky z-index-sticky top-0 " style="margin-bottom: 80px">
    <div class="row">
      <div class="col-12">
        <nav class="navbar navbar-expand-lg  blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
          <div class="container-fluid">
            <a class="navbar-brand font-weight-bolder ms-sm-3" 
               href="/" rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom">
              Newspaper Agency
            </a>
            <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
            </button>
            <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0" id="navigation">
              <ul class="navbar-nav navbar-nav-hover ms-lg-12 ps-lg-5 w-100">
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a href="{% url 'newspaper:topic-list' %}" class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center">
                    Topics
                  </a>
                </li>
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a href="{% url 'newspaper:newspaper-list' %}" class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center">
                    Newspapers
                  </a>
                </li>
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a href="{% url 'newspaper:redactor-list'%}" class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center">
                    Team List
                  </a>
                </li>
                <li class="nav-item dropdown dropdown-hover mx-2">
                  {% if request.user.is_authenticated %}
                  <a href="{% url 'newspaper:redactor-detail' pk=request.user.id %}" class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center">
                    Me
                  </a>
                  {% endif %}
                </li>

                <li class="nav-item ms-lg-auto">
                  {% if request.user.is_authenticated %}
                    <a class="nav-link nav-link-icon me-2" href="{% url 'newspaper:logout' %}">
                    <i class="fa fa-sign-out me-1"></i>
                    <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Logout">Logout</p>
                    </a>
                  {% endif %}
                </li>
                <li class="nav-item my-auto ms-3 ms-lg-0">
                  {% if request.user.is_authenticated %}
                  <a href="https://github.com/oigod"
                     target="_blank"
                     class="btn   bg-gradient-primary btn-round mb-0 me-1 mt-2 mt-md-0">GIT Hub</a>
                  {% endif %}
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <!-- End Navbar -->
      </div>
    </div>
  </div>

templates/includes/pagination.html
{% load query_transform %}

{% if is_paginated %}
  <nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?{% query_transform request page=page_obj.previous_page_number %}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
      {% endif %}
      {% for page_num in page_obj.paginator.page_range %}
        {% if page_obj.number == page_num %}
          <li class="page-item active">
            <span class="page-link">{{ page_num }} <span class="sr-only">(current)</span></span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?{% query_transform request page=page_num %}">{{ page_num }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?{% query_transform request page=page_obj.next_page_number %}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

templates/includes/scripts.html
  <script src="{{ ASSETS_ROOT }}/js/core/popper.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/core/bootstrap.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/perfect-scrollbar.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/prism.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/parallax.min.js"></script>