newspaper/urls.py
from django.conf.urls.static import static
from django.urls import path
from django.conf import settings
from . import views

app_name = "newspaper"


urlpatterns = [
    path("", views.index, name="index"),
    path("topics/", views.TopicListView.as_view(), name="topic-list"),
    path("topics/create/", views.TopicCreateView.as_view(), name="topic-create"),
    path("topics/<int:pk>/update/", views.TopicUpdateView.as_view(), name="topic-update"),
    path("topics/<int:pk>/delete/", views.TopicDeleteView.as_view(), name="topic-delete"),
    path("topics/<int:pk>/", views.TopicDetailView.as_view(), name="topic-detail"),
    path("newspapers/create/", views.NewspaperCreateView.as_view(), name="newspaper-create"),
    path("newspapers/<int:pk>/", views.NewspaperDetailView.as_view(), name="newspaper-detail"),
    path("newspapers/<int:pk>/update/", views.NewspaperUpdateView.as_view(), name="newspaper-update"),
    path("newspapers/<int:pk>/delete/", views.NewspaperDeleteView.as_view(), name="newspaper-delete"),
    path("newspapers/", views.NewspaperListView.as_view(), name="newspaper-list"),
    path("redactors/<int:pk>/", views.RedactorDetailView.as_view(), name="redactor-detail"),
    path("redactors/list/", views.RedactorListView.as_view(), name="redactor-list"),
    path("redactors/<int:pk>/delete/", views.RedactorDeleteView.as_view(), name="redactor-delete"),
    path("redactors/<int:pk>/update/", views.RedactorUpdateView.as_view(), name="redactor-update"),
    path("sign-in/", views.LoginView.as_view(), name="sign-in"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("sign-up/", views.RedactorCreateView.as_view(), name="sign-up"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newspaper_agency/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('newspaper.urls', namespace='newspaper')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newspaper/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Topic(models.Model):
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    short_description = models.CharField(max_length=255)
    image = models.ImageField(upload_to="images/%Y/%m/%d/", blank=True, null=True)

    def __str__(self) -> str:
        """Return a string representation of the model."""
        return self.name


class Redactor(AbstractUser):
    years_of_experience = models.DecimalField(max_digits=3, decimal_places=1, default=0.0)

    class Meta:
        verbose_name_plural = "redactors"
        verbose_name = "redactor"

    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"

    def __str__(self) -> str:
        """Return a string representation of the model."""
        return f"{self.first_name} {self.last_name} {self.years_of_experience}"


class Newspaper(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    published_date = models.DateTimeField(auto_now_add=True)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, related_name="newspapers")
    publishers = models.ManyToManyField(Redactor, related_name="newspapers")
    image = models.ImageField(upload_to="images/%Y/%m/%d/", blank=True, null=True)

    class Meta:
        verbose_name_plural = "newspapers"
        verbose_name = "newspaper"

    def __str__(self) -> str:
        """Return a string representation of the model."""
        return self.title

newspaper/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from newspaper.models import Redactor, Newspaper


class RedactorCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Redactor
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "years_of_experience",
        )

    def clean_years_of_experience(self):
        return validate_years_of_experience(self.cleaned_data["years_of_experience"])


class NewspaperForm(forms.ModelForm):
    publishers = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Newspaper
        fields = "__all__"


class NewspaperSearchForm(forms.Form):
    title = forms.CharField(
        required=False,
        max_length=255,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Title"}),
    )


class TopicSearchForm(forms.Form):
    name = forms.CharField(
        required=False,
        max_length=255,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Name"}),
    )


class RedactorUpdateForm(forms.ModelForm):
    class Meta:
        model = Redactor
        fields = ["first_name", "last_name", "years_of_experience"]

    def clean_years_of_experience(self):
        return validate_years_of_experience(self.cleaned_data["years_of_experience"])


def validate_years_of_experience(years_of_experience):
    if years_of_experience < 0:
        raise ValidationError("Years of experience should be positive")
    elif years_of_experience > 100:
        raise ValidationError("Years of experience should be less than 100")

    return years_of_experience

newspaper/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.contrib.auth import views as auth_views

from newspaper.forms import RedactorCreationForm, NewspaperForm, NewspaperSearchForm, TopicSearchForm, \
    RedactorUpdateForm
from newspaper.models import Redactor, Topic, Newspaper


@login_required(login_url=reverse_lazy("newspaper:sign-in"))
def index(request):
    """View function for the home page of the site."""

    count_redactors = Redactor.objects.count()
    count_newspapers = Newspaper.objects.count()
    count_topics = Topic.objects.count()

    count_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = count_visits + 1

    context = {
        "count_redactors": count_redactors,
        "count_newspapers": count_newspapers,
        "count_topics": count_topics,
        "count_visits": count_visits + 1,
    }

    return render(request, "newspaper/index/index.html", context=context)


class TopicListView(LoginRequiredMixin, generic.ListView):
    model = Topic
    context_object_name = "topic_list"
    template_name = "newspaper/newspaper_lists/topic_list.html"
    paginate_by = 4
    login_url = reverse_lazy("newspaper:sign-in")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TopicListView, self).get_context_data(**kwargs)

        context["search_form"] = TopicSearchForm()

        return context

    def get_queryset(self):
        queryset = Topic.objects.all()
        name = self.request.GET.get("name")

        if name:
            return queryset.filter(name__icontains=name)

        return queryset


class TopicCreateView(LoginRequiredMixin, generic.CreateView):
    model = Topic
    fields = "__all__"
    template_name = "newspaper/newspaper_forms/topic_form.html"
    success_url = reverse_lazy("newspaper:topic-list")
    login_url = reverse_lazy("newspaper:sign-in")


class TopicDetailView(LoginRequiredMixin, generic.DetailView):
    model = Topic
    template_name = "newspaper/newspaper_details/topic_detail.html"
    login_url = reverse_lazy("newspaper:sign-in")


class TopicUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Topic
    fields = "__all__"
    template_name = "newspaper/newspaper_forms/topic_form.html"
    success_url = reverse_lazy("newspaper:topic-list")
    login_url = reverse_lazy("newspaper:sign-in")


class TopicDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Topic
    template_name = "newspaper/newspaper_confirms/topic_confirm_delete.html"
    success_url = reverse_lazy("newspaper:topic-list")
    login_url = reverse_lazy("newspaper:sign-in")


class NewspaperListView(LoginRequiredMixin, generic.ListView):
    model = Newspaper
    context_object_name = "newspaper_list"
    template_name = "newspaper/newspaper_lists/newspaper_list.html"
    paginate_by = 4
    login_url = reverse_lazy("newspaper:sign-in")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(NewspaperListView, self).get_context_data(**kwargs)

        context["search_form"] = NewspaperSearchForm()

        return context

    def get_queryset(self):
        queryset = Newspaper.objects.select_related("topic")
        title = self.request.GET.get("title")

        if title:
            return queryset.filter(title__icontains=title)

        return queryset


class NewspaperDetailView(LoginRequiredMixin, generic.DetailView):
    model = Newspaper
    template_name = "newspaper/newspaper_details/newspaper_detail.html"
    login_url = reverse_lazy("newspaper:sign-in")


class NewspaperCreateView(LoginRequiredMixin, generic.CreateView):
    form_class = NewspaperForm
    model = Newspaper
    success_url = reverse_lazy("newspaper:newspaper-list")
    template_name = "newspaper/newspaper_forms/newspaper_form.html"
    login_url = reverse_lazy("newspaper:sign-in")


class NewspaperUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("newspaper:newspaper-list")
    template_name = "newspaper/newspaper_forms/newspaper_form.html"
    login_url = reverse_lazy("newspaper:sign-in")


class NewspaperDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Newspaper
    success_url = reverse_lazy("newspaper:newspaper-list")
    template_name = "newspaper/newspaper_confirms/newspaper_confirm_delete.html"
    login_url = reverse_lazy("newspaper:sign-in")


class RedactorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Redactor
    context_object_name = "redactor"
    template_name = "newspaper/newspaper_details/redactor_detail.html"
    login_url = reverse_lazy("newspaper:sign-in")


class RedactorListView(LoginRequiredMixin, generic.ListView):
    model = Redactor
    context_object_name = "redactor_list"
    template_name = "newspaper/newspaper_lists/redactor_list.html"
    paginate_by = 5
    login_url = reverse_lazy("newspaper:sign-in")

    class Meta:
        ordering = ["name"]


class RedactorDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Redactor
    success_url = "/"
    template_name = "newspaper/newspaper_confirms/redactor_confirm_delete.html"
    login_url = reverse_lazy("newspaper:sign-in")


class RedactorUpdateView(LoginRequiredMixin, generic.UpdateView):
    form_class = RedactorUpdateForm
    model = Redactor

    template_name = "newspaper/newspaper_forms/redactor_form.html"
    login_url = reverse_lazy("newspaper:sign-in")

    def form_valid(self, form):
        form.save()
        return redirect(reverse("newspaper:redactor-detail", kwargs={"pk": self.object.pk}))


class LoginView(auth_views.LoginView):
    template_name = "registration/page-sign-in.html"
    success_url = reverse_lazy("newspaper:index")

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(self.success_url)
        return super().get(request, *args, **kwargs)


class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
    next_page = reverse_lazy("newspaper:sign-in")
    template_name = "registration/page-sign-in.html"
    login_url = reverse_lazy("newspaper:sign-in")


class RedactorCreateView(generic.CreateView):
    model = Redactor
    form_class = RedactorCreationForm
    template_name = "registration/page-sign-up.html"
    success_url = reverse_lazy("newspaper:index")

newspaper/templates/newspaper/newspaper_lists/newspaper_list.html
{% extends 'base-template.html' %}
{% load crispy_forms_filters %}

{% block title %} News {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} blog-author bg-gray-100 {% endblock body_class %}

{% block content %}

  {% include "includes/navigation.html" %}

  <section class="py-3">
    <div class="container">
      <div class="row">
        <div class="col-lg-6">
          <h3 class="mb-5">Our Newspapers:</h3>
        </div>
      </div>
      <div class="row">
      <form action="" method="get" class="form-inline my-3">
        {% csrf_token %}
        <div class="input-group">
          {{ search_form|crispy }}
          <div class="input-group-append">
            <button class="btn btn-primary" type="submit">
              <i class="fas fa-search"></i>
            </button>
            <a href="{% url 'newspaper:newspaper-create' %}" class="btn btn-primary">
                  Create
            </a>
          </div>
        </div>
      </form>

        {% for newspaper in newspaper_list %}
          <div class="col-lg-3 col-sm-6">
          <div class="card card-plain card-blog">
            <div class="card-image border-radius-lg position-relative">
              <a href="javascript:;">
                {% if newspaper.image %}
                <img class="w-100 border-radius-lg move-on-hover shadow" src="{{ newspaper.image.url }}">
                {% endif %}
              </a>
            </div>
            <div class="card-body px-0">
              <h5>
                <a href="javascript:;" class="text-dark font-weight-bold">{{ newspaper.title }}</a>
              </h5>
              <p>
                {{ newspaper.content|truncatechars:100}}
                <b></b>
                <h5>
                  Written by:
                  {% for redactor in newspaper.publishers.all %}
                    <a href="{% url 'newspaper:redactor-detail' pk=redactor.id %}"> {{ redactor.username }}</a>
                  {% endfor %}
                </h5>
              </p>
              <a href="{% url 'newspaper:newspaper-detail' pk=newspaper.id %}" class="text-info icon-move-right">Read More
                <i class="fas fa-arrow-right text-sm"></i>
              </a>
            </div>
          </div>
        </div>
        {% endfor %}
        </div>
      </div>
    </div>
  </section>


{% endblock content %}
{% block footer %}

{% endblock %}

<!-- Specific JS goes HERE -->
{% block javascripts %}

  <script src="{{ ASSETS_ROOT }}/js/soft-design-system.min.js?v=1.0.1" type="text/javascript"></script>

{% endblock javascripts %}

newspaper/templates/newspaper/newspaper_lists/redactor_list.html
{% extends 'base-template.html' %}
{% load crispy_forms_filters %}

{% block title %} Team {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} blog-author bg-gray-100 {% endblock body_class %}

{% block content %}

  {% include "includes/navigation.html" %}

  <section class="py-3">

    <div class="table-responsive">
      <table class="table">
      <thead>
        <tr>
          <th scope="col">id</th>
          <th scope="col">Full Name</th>
          <th scope="col">Newspapers</th>
          <th scope="col">Username</th>
        </tr>
      </thead>

      <tbody>
      {% for redactor in redactor_list %}
        <tr>
          <td><a href="{% url 'newspaper:redactor-detail' pk=redactor.id %}">{{ redactor.id }}</a></td>
          <td>{{ redactor.first_name }} {{ redactor.last_name }}{% if request.user.id == redactor.id %} (Me){% endif %}</td>
          <td>{{ redactor.newspapers.count }}</td>
          <td>{{ redactor.username }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
    </div>
        </div>
      </div>
    </div>
  </section>


{% endblock content %}
{% block footer %}

{% endblock %}

<!-- Specific JS goes HERE -->
{% block javascripts %}

  <script src="{{ ASSETS_ROOT }}/js/soft-design-system.min.js?v=1.0.1" type="text/javascript"></script>

{% endblock javascripts %}

newspaper/templates/newspaper/newspaper_lists/topic_list.html
{% extends 'base-template.html' %}
{% load crispy_forms_filters %}

{% block title %} Topics {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} blog-author bg-gray-100 {% endblock body_class %}

{% block content %}

  {% include "includes/navigation.html" %}


  <section class="py-3">
    <div class="container">
      <div class="row">
        <div class="col-lg-6">
          <h3 class="mb-5">Our Topics:</h3>
        </div>
      </div>
      <div class="row">
          <form action="" method="get" class="form-inline my-3">
            {% csrf_token %}
            <div class="input-group">
              {{ search_form|crispy }}
              <div class="input-group-append">
                <button class="btn btn-primary" type="submit">
                  <i class="fas fa-search"></i>
                </button>
                <a href="{% url 'newspaper:topic-create' %}" class="btn btn-primary">
                  Create
                </a>
              </div>
            </div>
          </form>
        {% if topic_list %}
        {% for topic in topic_list %}
          <div class="col-lg-3 col-sm-6">
          <div class="card card-plain card-blog">
            <div class="card-image border-radius-lg position-relative">
              <a href="{% url 'newspaper:topic-detail' pk=topic.id %}">
                {% if topic.image %}
                <img class="w-100 border-radius-lg move-on-hover shadow" src="{{ topic.image.url }}">
                {% endif %}
              </a>
            </div>
            <div class="card-body px-0">
              <h5>
                <a href="javascript:;" class="text-dark font-weight-bold">{{ topic.name }}</a>
              </h5>
              <p>
                {{ topic.short_description }}
              </p>
              <a href="{% url 'newspaper:topic-update' pk=topic.id %}" class="text-info icon-move-right">Edit this Topic
                <i>|</i>
              </a>
              <a href="{% url 'newspaper:topic-detail' pk=topic.id %}" class="text-info icon-move-right">Read More
                <i class="fas fa-arrow-right text-sm"></i>
              </a>
            </div>
          </div>
        </div>
        {% endfor %}
          {% else %}
          No Topics yet.
      {% endif %}
        </div>
      </div>
    </div>
  </section>


{% endblock content %}
{% block footer %}

{% endblock %}

<!-- Specific JS goes HERE -->
{% block javascripts %}

  <script src="{{ ASSETS_ROOT }}/js/soft-design-system.min.js?v=1.0.1" type="text/javascript"></script>

{% endblock javascripts %}